### ISSUE TITLE
Issue faced when running genie using remote NLP server

### ISSUE THREAD

**Issue by varunSabnis** [stanford-oval/genie-sdk#5]
I ran the genie server with the remote NLP server option.  I have added the weather skill through the genie UI served locally from 127.0.0.1:3000. I am not getting a valid response in the genie chat when asked for the weather. I believe I see parse errors in the console. Please find attach screenshots of the console output and the genie response. Please let me know if I am missing something. Thanks!

![genie](https://user-images.githubusercontent.com/16621521/159830656-045d40d7-8db4-482d-a120-34c679b0a398.png)
![genie2](https://user-images.githubusercontent.com/16621521/159830666-24091960-3865-4312-ac07-a75599727f81.png)

**Comment by sileix** [comment]
Hi, @varunSabnis, sorry for the late reply. It costs us quite some time to figure out the reason for this bug. It turns out huggingface updated the config file of `bart-large` model, which broke our parser. See discussion [here](https://github.com/huggingface/transformers/issues/15559#issuecomment-1057235386). We have switched to `bart-base` as a temporary fix and we will switch back once we patch our software.

**Comment by varunSabnis** [comment]
Hi @rayslxu Thanks for letting me know!
